# -*- coding: utf-8 -*-
"""Alunoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IkF1-wojuSlUys2y4UmoktmUCKHzqVkQ
"""

a = 0
b = 3
if a == 0: 
    print(f'a recebeu{a}')
elif a == 3:
    print(f' a recebeu {b}')

n1 = 2 
n2 = 5
n3 = 4
if n1 < n2:
    n3 = n1+n2
n3

nome = 'detergente'
print(len(nome))

print(nome[0:10])

a = 10
b = 3
a = b
c = a+b
b = 0
d = a + b
print(f'valor da variavel {c}')

lista = [5,4,2]
lista[1] = 10
print(lista)

sala = ['wollas', 'adryan', 'breno', 'fabio']
print(sala[1])
a = 'wollas'
print(a[1])
nome = 'antonio'
print(nome[1])

lista = lista+[11,22,73]
print(lista)